# Config spec template for SMM main latest branch.

# NOTE: Please do not edit.  This view is for "cctools"
# environment for all SMM developers.  It should be accessed
# via $PROJHOME as the view extended pathname:
#
#    /view/swtadmin_smm_cctools/millenniumvobs/smm_root/cctools
#

element * CHECKEDOUT
element * /main/LATEST -nocheckout

# end of template, generated by csgen
