# Config spec template for feature development.

element * CHECKEDOUT
element * .../dev_ne_mmc2.0/LATEST

# pick next line to use a label as branch off point
# (note that this may be used in addition to line below)
# element * <release_label> -mkbranch dev_ne_mmc2.0

# pick next line to use main latest as branch off point
# (note that you must use this when merging to main)
element * /main/LATEST -mkbranch dev_ne_mmc2.0

# end of template, generated by csgen
