# Config spec template for SMM main project branch.

element * CHECKEDOUT
element * /main/smm_main/LATEST

# The line below is ONLY to view directories, since they
# are not branched by our import from CVS.
element * /main/LATEST -nocheckout

# end of template, generated by csgen
