Date: Wed, 10 May 1995 12:27 -0400 (EDT)
From: "Bruce E Letendre%RAY_EDMAR_M_C"@ccmail.ed.ray.com
Subject: Thank You
To: "Kent J Arnold%RAY_EDSUD_F"@ccmail.ed.ray.com,
 "Brian S Lingard%RAY_EDSUD_F"@ccmail.ed.ray.com,
 "Alan P Aremburg%RAY_EDMAR_F"@ccmail.ed.ray.com,
 "Carl A Morth%RAY_EDMAR_G"@ccmail.ed.ray.com,
 "Christopher M Mahoney%RAY_EDMAR_G"@ccmail.ed.ray.com,
 "June E Melanson%RAY_EDSUD_M_F"@ccmail.ed.ray.com,
 "James E Lavallee%RAY_EDMAR_E"@ccmail.ed.ray.com,
 "Scott A(VINES) Thompson%VINES"@ccmail.ed.ray.com,
 "Norman W Palmer%RAY_EDMAR_G"@ccmail.ed.ray.com,
 "Ann Diep%RAY_EDMAR_G"@ccmail.ed.ray.com, celeste@xyvision.com,
 Steven_Mango%VINES@ccmail.ed.ray.com,
 "Daniel M Loach%RAY_EDMAR_G"@ccmail.ed.ray.com,
 "Stephen P Robinson%RAY_EDMAR_D"@ccmail.ed.ray.com,
 "Laurie A Robinson%RAY_EDSUD_M_G"@ccmail.ed.ray.com,
 David_M_Biernacki@ccmail.ed.ray.com,
 "David J Macannuco%RAY_EDMAR_H"@ccmail.ed.ray.com,
 "Paul J Stephenson%RAY_EDMAR_G"@ccmail.ed.ray.com,
 "Charles N Cheatwood%RAY_EDMAR_G"@ccmail.ed.ray.com,
 "Donald D Abells%RAY_EDMAR_G"@ccmail.ed.ray.com
MIME-version: 1.0

Hi,

Paul, Keith and I would like to take this time to thank you in advance for 
accepting our invitation as follows:

We're moving again, and boy do we need help.  It won't be as bad as last year 
(two third floor apartments).  Both houses are split entry so only a half 
flight of stairs will be required at each end.  Paul, Keith and I are moving 
boxes in advance, so all that will be left is furniture and a few boxes.  We 
have a nice 24 foot truck for easy packing/unpacking.  We'll even have some 
music at the destination for your listening pleasure.  Cheese and wine will be 
served, topped off by champagne, Cornish game hens, leg of lamb and a tasty 
chocolate mousse (menu is subject to change).

Loading the truck (a lovely orange and silver with a touching silhouette of 
Americana) will take place on Saturday, May 20, 1995 at 62 Nashoba Drive in 
beautiful uptown Marlborough at approximately 8:30 - 9:00 a.m.  You will then 
be whisked off to the fabulous destination hot spot of 82 Raffaele Road, 
Marlborough (5 stars in last month's Travel magazine).

DIRECTIONS to 64 Nashoba Drive:  Ask someone who knows.

DIRECTIONS to 82 Raffaele Road:  Take Route 20 to Hosmer Street, go past Royal 
Crest, past Spoon Hill Ave. (on right), Raffaele Road is the next right.  Once 
on Raffaele Road continue straight until you see a left hand turn, Raffaele 
Road continues and ends in a cul de sac, 82 Raffaele Road is the first house on 
your left just after the left hand turn.  The house is a sharp white with 
stunning lime green shutters (a sight not to be missed).

If you have any questions please direct them to either Paul, Keith or myself.

Once again, Paul, Keith and I thank you for your continued support in our quest 
of getting you lazy slobs to move us every year.
