/*****************************************************************************
 *
 *  Program for converting icon file format to PPM image format.
 *
 *	File:	icon2ppm.c
 *
 *	Author: Brian Lingard
 *
 *	Date:	10/09/97
 *
 *	Revisions:
 * 	  0.0	10/09/97  originated
 *
 *	Usage:
 *
 *	  icon2ppm [infile.icn] [outfile.ppm]
 *
 *	Examples:
 *
 *	  icon2ppm starship.icn starship.ppm
 *
 *****************************************************************************/


#include <stdio.h>

#ifndef _PPM_H
#include "ppm.h"
#endif

#ifndef _ICON_H
#include "icon.h"
#endif


#ifndef COLOR_S_T
typedef struct {
   unsigned char r;
   unsigned char g;
   unsigned char b;
} COLOR_S_T;
#endif


/*  define some constants
 */

#define MAX_R_SIZE	800
#define MAX_C_SIZE	800

#define INPUT_FILE_NAME		"infile.icn"
#define OUTPUT_FILE_NAME	"outfile.ppm"
#define LOG_FILE_NAME		"icon2ppm.log"


/*  LoadIcon - loads icon file                                          
 *                                                                    
 *  Parameters:
 *	icon	- pointer to icon structure
 *	R	- size of image in Y (rows)
 *	C	- size of image in X (columns)
 *	raster	- pointer to image raster array
 *
 *  Returns:
 *
 */
void
LoadIcon(FILE *fp, ICON_S_T *iconptr)
{
   int 			r, c;
   ICON_TYPE_T		type;
   pointType 		size, topl;
   unsigned char	red, green, blue;
   int			nc, pixel;

   fscanf(fp, "%d\n", &type);
   iconptr->type = type;

   fscanf(fp, "%d %d %d %d\n", &size.x, &size.y, &topl.x, &topl.y);
   iconptr->size.x = size.x;
   iconptr->size.y = size.y;
   iconptr->top_left.x = topl.x;
   iconptr->top_left.y = topl.y;

   fscanf(fp, "%d\n", &nc);
   iconptr->num_colors = nc;

   for (c = 0; c < iconptr->num_colors; c++)
   {
      fscanf(fp, "%c %c %c\n", &red, &green, &blue );

      iconptr->colormap.map[c][R_IDX] = red;
      iconptr->colormap.map[c][G_IDX] = green;
      iconptr->colormap.map[c][B_IDX] = blue;
   }

   for (r = 0; r < iconptr->size.y; r++)
   {
      for (c = 0; c < iconptr->size.x; c++)
      {
          fscanf(fp, "%d ", &pixel);
          iconptr->pixmap[r][c] = pixel;
      }
      fscanf(fp, "\n");
   }
}


/*  CopyIcon2Raster - copies icon data to raster image
 *
 *  Parameters:
 *	icon	- pointer to icon structure
 *	R	- size of image in Y (rows)
 *	C	- size of image in X (columns)
 *	raster	- pointer to image raster array
 *
 *  Returns:
 *	
 */
void
CopyIcon2Raster(ICON_S_T *icon, int R, int C, COLOR_S_T *raster)
{
   int r, c;
   char *ras_p;
   int idx;

   ras_p = (char *)raster;

   for (r = 0; r < R; r++)
   {
      for (c = 0; c < C; c++)
      {
         idx = icon->pixmap[r][c];
         *(ras_p++) = icon->colormap.map[idx][R_IDX];
         *(ras_p++) = icon->colormap.map[idx][G_IDX];
         *(ras_p++) = icon->colormap.map[idx][B_IDX];
      }
   }
}


/*  main	- main program
 *
 *  Parameters:
 *	argc	- number of command line arguments
 *	argv	- pointer to command line argument array
 *
 *  Returns:
 *	none
 */
void 
main(int argc, char **argv)
{
   int 		r_size, c_size;
   int 		type;

   char 	*infile, *outfile;

   FILE 	*readfile, *writefile, *logfile;
   ICON_S_T 	icon;
   COLOR_S_T 	raster[MAX_R_SIZE][MAX_C_SIZE];


   /*  handle input args
    */
   if (argc == 1)
   {
      infile = INPUT_FILE_NAME;
      outfile = OUTPUT_FILE_NAME;
   }
   else
   {
      infile = argv[1];
      outfile = argv[2];
   }

   /*  read image as icon file
    */
   readfile = fopen(infile, "r");
   if (readfile == (FILE *)NULL)
   {
      printf("Main: error opening %s to read\n", infile);
      exit(1);
   }
   else
   {
      printf("reading icon file ...\n");

      LoadIcon( readfile, &icon );
   }

   /*  copy icon to PPM 
    */
   r_size = icon.size.y;
   c_size = icon.size.x;
   CopyIcon2Raster( &icon, r_size, c_size, &raster[0][0] );

   /*  save image as PPM file
    */
   writefile = fopen(outfile, "w");
   if (writefile == (FILE *)NULL)
   {
      printf("Main: error opening %s to write\n", outfile);
      exit(1);
   }
   else
   {
      printf("writing PPM file ...\n");

      PPM_write(writefile, (char *)&raster[0][0], 
			r_size, c_size, "generated by icon2ppm v1.0");
   }

   exit(0);
}
