#!/bin/bash
#
# bootping -- power cycles a module via the terminal server hookup
#             and verifies the modules are up by pinging them
#

loopcount=1
ontime=20
offtime=20

if [ $# -eq "3" ]
then
	ontime=$2
	offtime=$3
fi

if [ $# -eq "2" ]
then
	ontime=$2
fi

if [ $# -lt "1" ]
then
	echo "Usage: bootping <count> [<ontime> <offtime>]"
	echo "i.e.:  bootping 10"
	echo "i.e.:  bootping 10 30"
	echo "i.e.:  bootping 10 30 5"
	exit
fi

loopcount=$1

ipmain=10.2.32.47
ipvow=10.2.32.51

portmain=8000
portvow=8001

current=1

echo " "
echo "BOOTPING TEST - starting ..."
echo "BOOTPING TEST - ............ loopcount $loopcount ..."
echo "BOOTPING TEST - ............ ontime $ontime seconds ..."
echo "BOOTPING TEST - ............ offtime $offtime seconds ..."
echo " "

while [[ $current -le $loopcount ]] 
do
	echo " "
	echo "BOOTPING TEST - loop $current start"
	echo " "

	power-ctl 1
	sleep $ontime
        ping-exp $ipmain 256 3
        ping-exp $ipvow 256 3
        sleep 1
	power-ctl 0

	echo " "
	echo "BOOTPING TEST - loop $current end"
	echo " "
	sleep $offtime

	let current=$current+1
done

echo " "
echo "BOOTPING TEST - done."
echo " "

exit

