#!/usr/bin/expect
# buttonknob-exp: 
#
# Uses System Debug Console to exercise button/knob commands
#
# Usage: buttonknob-exp <ipaddr>
#       ipaddr         - IP Address of modules
#
# Type: expect
#
# NOTES:
#       - MUST be started when system is in Tuner UI
#
#
# 1.1   11/05/2005      BSL     Updated for use by Program Source
# 1.0	04/05/2001	BSL	Initial version.
#
##########################################################

# Initialize variables
set testresult "UNKNOWN"

set timeout10 10;		# Set timeout (10 sec)

set timeout3 3;			# Set timeout (3 sec)

set tcpport 7072;               # tcp port of system debug interface


# Get command line arguments
if {$argc != 1} {
	puts "Usage:  $argv0 <ipaddr>"
	exit
}

set ipaddr [lindex $argv 0];	# AC outlet port number 


set resultfile [open "~/var/buttonknobexp-$ipaddr.log" "w"]


#****************************************************
# Procedure: setbuttonknob()
#****************************************************
proc setbuttonknob { id } {
	send "diag app bkt $id\r"
        expect {
               timeout10 {
		       set testresult "FAIL"
	               puts "\nModule is not running\n"
	       }
               "OK" {
	               set testresult "PASS"
	       }
        }
        sleep 5
}

#******************TOP of LOOP***********************

spawn bash
expect "$"

send "telnet $ipaddr $tcpport \r"
expect {
	timeout10 {
		set testresult "FAIL"
		puts "\nTELNET to Terminal Server TIMED OUT\n"
	}
	"Connection refused" {
		set testresult "BUSY"
		puts "\nTCP port $tcpport is busy, try again in a few seconds."
	}
	"SysDbg>" {
		set testresult "ACTIVE"

		send "\r"
                expect {
                	timeout10 {
		                set testresult "FAIL"
	                	puts "\nModule is not running\n"
	                }
                	"SysDbg>" {
	         	        set testresult "PASS"
	                }
                }
                sleep 1

		send "diag session start\r"
                expect {
                	timeout10 {
		                set testresult "FAIL"
	                	puts "\nModule is not running\n"
	                }
                	"OK" {
	         	        set testresult "PASS"
	                }
                }
                sleep 1

		send "system chsrc diag\r"
                expect {
                	timeout10 {
		                set testresult "FAIL"
	                	puts "\nModule is not running\n"
	                }
                	"OK" {
	         	        set testresult "PASS"
	                }
                }
                sleep 3

		send "diag app bkt enter\r"
                expect {
                	timeout10 {
		                set testresult "FAIL"
	                	puts "\nModule is not running\n"
	                }
                	"OK" {
	         	        set testresult "PASS"
	                }
                }
                sleep 1

                # start buttons
                setbuttonknob 0x00        
                setbuttonknob 0x01
                setbuttonknob 0x02
                setbuttonknob 0x03
                setbuttonknob 0x04
                setbuttonknob 0x05
                setbuttonknob 0x06
                setbuttonknob 0x07
                setbuttonknob 0x08
                setbuttonknob 0x09
                setbuttonknob 0x0a
                setbuttonknob 0x0b
                setbuttonknob 0x0c
                setbuttonknob 0x0d
                setbuttonknob 0x0e
                setbuttonknob 0x0f     

                # right knob push
                setbuttonknob 0x10      
                # left knob push
                setbuttonknob 0x11       

                # knobs cw
                setbuttonknob 0x12      
                setbuttonknob 0x13
                setbuttonknob 0x14
                setbuttonknob 0x15

                # knobs ccw
                setbuttonknob 0x16       
                setbuttonknob 0x17
                setbuttonknob 0x18
                setbuttonknob 0x19

		send "diag app bkt exit\r"
                expect {
                	timeout10 {
		                set testresult "FAIL"
	                	puts "\nModule is not running\n"
	                }
                	"OK" {
	         	        set testresult "PASS"
	                }
                }
                sleep 1
		
                send "exit\r"
		expect {
			timeout3 {
		                set testresult "FAIL"
                                puts "\nSysDbg exit TIMED OUT\n"
			}
			"$" {

			}
		}

	}
}

send "exit\r"; # Exit ksh
close; # Close spawned process
wait;  # Wait for ksh to "exit"

#****************BOTTOM of LOOP**********************
puts $resultfile "buttonknobexp $ipaddr - $testresult"
close $resultfile

exit

