#!/usr/bin/expect
# dtctest-exp: 
#
# Uses System Debug Console to retreive stored DTC data
#
# Usage: dtctest-exp <ipaddr>
#       ipaddr         - IP Address of modules
#
# Type: expect
#
# 1.1   11/05/2005      BSL     Updated for use by Program Source
# 1.0	04/05/2001	BSL	Initial version.
#
##########################################################

# Initialize variables
set testresult "UNKNOWN"

set timeout10 10;		# Set timeout (10 sec)

set timeout3 3;			# Set timeout (3 sec)

set tcpport 7072;               # tcp port of system debug interface


# Get command line arguments
if {$argc != 1} {
	puts "Usage:  $argv0 <ipaddr>"
	exit
}

set ipaddr [lindex $argv 0];	# AC outlet port number 


set resultfile [open "~/var/dtctestexp-$ipaddr.log" "w"]


#****************************************************
# Procedure: getdtc()
#****************************************************
proc getdtc { id } {
	send "diag dtc read $id\r"
        expect {
                timeout10 {
                        set testresult "FAIL"
                        puts "\nModule is not running\n"
                }
                "OK" {
                        set testresult "PASS"
                }
        }
}

#******************TOP of LOOP***********************

spawn bash
expect "$"

send "telnet $ipaddr $tcpport \r"
expect {
	timeout10 {
		set testresult "FAIL"
		puts "\nTELNET to Terminal Server TIMED OUT\n"
	}
	"Connection refused" {
		set testresult "BUSY"
		puts "\nTCP port $tcpport is busy, try again in a few seconds."
	}
	"SysDbg>" {
		set testresult "ACTIVE"

		send "\r"
                expect {
                	timeout10 {
		                set testresult "FAIL"
	                	puts "\nModule is not running\n"
	                }
                	"SysDbg>" {
	         	        set testresult "PASS"
	                }
                }

		getdtc 0xc100
		getdtc 0xc101
		getdtc 0xc110
		getdtc 0xc111
		getdtc 0xc112
		getdtc 0xc113
		getdtc 0xc150
		getdtc 0xc151
		getdtc 0xc152
		getdtc 0xc153
		getdtc 0xc154
		getdtc 0xc155
		getdtc 0xc160
		getdtc 0xc161
		getdtc 0xc164
		getdtc 0xc200
		getdtc 0xc250
		getdtc 0xc261
		getdtc 0xc600
		getdtc 0xc650
		getdtc 0xc651

		send "exit\r"
		expect {
			timeout3 {
		                set testresult "FAIL"
                                puts "\nSysDbg exit TIMED OUT\n"
			}
			"$" {

			}
		}

	}
}

send "exit\r"; # Exit ksh
close; # Close spawned process
wait;  # Wait for ksh to "exit"

#****************BOTTOM of LOOP**********************
puts $resultfile "tonetestexp $ipaddr - $testresult"
close $resultfile

exit

