#!/bin/sh
#
# ecuprog.sh

IP=192.168.0.10

echo "Programming Silverbox ECU data ..."

./mfinit-exp $IP

echo "Programming Tuner ECU data ..."

./mtinit-exp $IP

echo "Programming Disply ECU data ..."

./mdinit-exp $IP

echo "Done."

