#!/usr/bin/expect
# filecopy-exp: 
#
# Uses System Debug Console to copy files
#
# Usage: filecopy-exp <ipaddr> <srcfile> <destfile>
#       ipaddr         - IP Address of modules
#       srcfile        - source file path
#       destfile       - destination file path
#
# Examples:
#
#       filecopy-exp 192.168.0.10 /usb/file.bin d:/v0/file.bin          USB --> HDD
#       filecopy-exp 192.168.0.10 d:/v0/file.bin /usb/file.bin          HDD --> USB
#
# Type: expect
#
#
#
# 1.1   11/05/2005      BSL     Updated for use by Program Source
# 1.0	04/05/2001	BSL	Initial version.
#
##########################################################

# Initialize variables
set testresult "UNKNOWN"

set timeout10 10;		# Set timeout (10 sec)

set timeout3 3;			# Set timeout (3 sec)

set tcpport 7072;               # tcp port of system debug interface


# Get command line arguments
if {$argc != 3} {
	puts "Usage:  $argv0 <ipaddr> <srcfile> <destfile>"
	exit
}

set ipaddr [lindex $argv 0];	# AC outlet port number 
set srcfile [lindex $argv 1];
set destfile [lindex $argv 2];

set resultfile [open "~/var/filecopyexp-$ipaddr.log" "w"]


#****************************************************
# Procedure: dofilecopy()
#****************************************************
proc dofilecopy { src dest } {
	send "file main cp $src $dest\r"
        expect {
               timeout10 {
		       set testresult "FAIL"
	               puts "\nModule is not running\n"
	       }
               "OK" {
	               set testresult "PASS"
	       }
        }
        sleep 5
}

#******************TOP of LOOP***********************

spawn bash
expect "$"

send "telnet $ipaddr $tcpport \r"
expect {
	timeout10 {
		set testresult "FAIL"
		puts "\nTELNET to Terminal Server TIMED OUT\n"
	}
	"Connection refused" {
		set testresult "BUSY"
		puts "\nTCP port $tcpport is busy, try again in a few seconds."
	}
	"SysDbg>" {
		set testresult "ACTIVE"

		send "\r"
                expect {
                	timeout10 {
		                set testresult "FAIL"
	                	puts "\nModule is not running\n"
	                }
                	"SysDbg>" {
	         	        set testresult "PASS"
	                }
                }
                sleep 1

                dofilecopy $srcfile $destfile      

                send "exit\r"
		expect {
			timeout3 {
		                set testresult "FAIL"
                                puts "\nSysDbg exit TIMED OUT\n"
			}
			"$" {

			}
		}

	}
}

send "exit\r"; # Exit ksh
close; # Close spawned process
wait;  # Wait for ksh to "exit"

#****************BOTTOM of LOOP**********************
puts $resultfile "filecopyexp $ipaddr - $testresult"
close $resultfile

exit

