#!/bin/bash
#
# loopping -- verifies the modules are up by pinging them
#             in a continuous loop
#

loopcount=1
ontime=1
offtime=3

if [ $# -eq "3" ]
then
	ontime=$2
	offtime=$3
fi

if [ $# -eq "2" ]
then
	ontime=$2
fi

if [ $# -lt "1" ]
then
	echo "Usage: loopping <count> [<ontime> <offtime>]"
	echo "i.e.:  loopping 10"
	echo "i.e.:  loopping 10 30"
	echo "i.e.:  loopping 10 30 5"
	exit
fi

loopcount=$1

ipmain=10.2.32.47
ipvow=10.2.32.51

portmain=8000
portvow=8001

current=1


echo " "
echo "LOOPPING TEST - starting ..."
echo "LOOPPING TEST - ............ loopcount $loopcount ..."
echo "LOOPPING TEST - ............ ontime $ontime seconds ..."
echo "LOOPPING TEST - ............ offtime $offtime seconds ..."
echo " "

echo " "
echo "=============================="
startdatetime=`date +%D-%T`
echo "START -- $startdatetime"
echo "=============================="
echo " "

while [[ $current -le $loopcount ]] 
do
	echo " "
	echo "LOOPPING TEST - loop $current start"
	echo " "

        ping-exp $ipmain 256 3
	sleep $ontime
        ping-exp $ipvow 256 3

	echo " "
	echo "LOOPPING TEST - loop $current end"
	echo " "

	echo " "
	echo "=============================="
        loopdatetime=`date +%D-%T`
        echo "START -- $startdatetime"
        echo "LOOP  -- $loopdatetime"
	echo "=============================="
	echo " "

        sleep $offtime

	let current=$current+1
done

echo " "
echo "LOOPPING TEST - done."
echo " "

echo "=============================="
echo "START -- $startdatetime"
stopdatetime=`date +%D-%T`
echo "STOP  -- $stopdatetime"
echo "=============================="

exit

