#!/bin/bash
#
# sourcetest -- loops on calling source selection test
#

if [ $# -lt "2" ]
then
	echo "Usage: sourcetest <ipaddress>   <count>"
	echo "i.e.:  sourcetest 192.168.0.10  10"
	exit
fi

loopcount=$2

current=1

echo " "
echo "SOURCE TEST - starting ..."
echo "SOURCE TEST - ............ ipaddress $1 ..."
echo "SOURCE TEST - ............ loopcount $loopcount ..."
echo " "

while [[ $current -le $loopcount ]] 
do
	echo " "
	echo "SOURCE TEST - loop $current start"
	echo " "

        sourcetest-exp $1

	echo " "
	echo "SOURCE TEST - loop $current end"
	echo " "

	let current=$current+1
done

echo " "
echo "SOURCE TEST - done."
echo " "


